// Code generated by "stringer -type=errorCode"; DO NOT EDIT.

package gofbwriter

import "strconv"

const _errorCode_name = "ERR_EMPTY_FIRST_NAME"

var _errorCode_index = [...]uint8{0, 20}

func (i errorCode) String() string {
	if i < 0 || i >= errorCode(len(_errorCode_index)-1) {
		return "errorCode(" + strconv.FormatInt(int64(i), 10) + ")"
	}
	return _errorCode_name[_errorCode_index[i]:_errorCode_index[i+1]]
}
